### ISSUE TITLE
 DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by davidnewcomb** [ramybenaroya/ember-index#11]
`ember-index` has a dependency on ember-cli-babel 5.x but the majority of ember modules have moved up to version 6. The project still tries to pull in version 5 and as a result we get a deprecation notice.

> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: cafe-rouge -> ember-index -> ember-cli-babel

Please can you upgrade the module dependencies to remove this warning.
Using Ember v3 causes this message too.

**Comment by ramybenaroya** [comment]
fixed in https://github.com/ramybenaroya/ember-index/pull/12
