### ISSUE TITLE
Arguments to path.join must be strings error (again)

### ISSUE THREAD

**Issue by billdwhite** [ramybenaroya/ember-index#4]
I'm using ember-cli 1.13.12, node 0.12.0, npm 2.14.10 and ember 2.1.0.  I'm using ember-index to create a dynamic index.jsp file.  It worked great until I updated my project to the latest ember-cli, node, and ember versions.  While, it certainly could be something I screwed up in the configuration, I wonder if the api has changed that ember-index relies upon.  I'm getting this exception when using ember-index:

TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:471:13)
    at Class.<anonymous> (/myapp/node_modules/ember-index/index.js:31:32)
    at Array.forEach (native)
    at Class.module.exports.contentFor (/myapp/node_modules/ember-index/index.js:27:25)
    at /myapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1449:49
    at Array.reduce (native)
    at EmberApp.contentFor (/myapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1448:33)
    at replacement (/myapp/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:78:36)
    at String.replace (native)
    at /myapp/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:82:25

I was able to fix the issue by changing line 31 in index.js from this

`var contentFilePath = path.join(this.app.project.root, this.app.options.trees.app, content.file);`

to this: 

`var contentFilePath = path.join(this.app.project.root, this.app.options.trees.app._directoryPath, content.file);`

Am I missing something or is this an actual bug?

**Comment by ramybenaroya** [comment]
Hey, seems like a bug of ember-index with ember-cli 1.13.12. Will look into
that.

**Comment by ramybenaroya** [comment]
https://github.com/ramybenaroya/ember-index/commit/6c5b4025e2fb5ec95dc715198cd6c403b600cde2 checks if `this.app.options.trees.app` is a a [Directory](https://github.com/broccolijs/broccoli-source/blob/master/index.js#L3) which implements [**broccoliGetInfo** ](https://github.com/broccolijs/broccoli-source/blob/master/index.js#L22)
